version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - jsouza_data:/var/lib/mysql

volumes:
  jsouza_data:
